### PR TITLE
Additions

### PR DESCRIPTION
**Pull request by TechnologyClassroom**
Added kltettres, Articulate, KAnagram, KWordQuiz, parley, Kiten, Tux Math, KBrunch, Kig, KmPlot, Qalculate, Cantor, KAlgebra, Rocs, OpenStreetMap, KGeography, Marble, LabPlot, KStars, Kalzium, Step, Minuet, Music Blocks, KTouch, Klavaro, TIPP10, Tux Typing, GNU Typist, KTurtle, Blockly, Lua, Python, Pygame, Processing, Octave, DebianEdu/Skolelinux, Debian, Ubuntu, Trisquel, and FocusWriter.

### CODE REVIEW

**Comment by zefanja** [comment]
Thanks again! Great additions!

**Comment by TechnologyClassroom** [comment]
You are welcome!

There are some other programs listed in the package lists for the Edubuntu metapackages.  Edubuntu as a distro is not updated anymore, but the project still exists as a metapackage for modern versions of Ubuntu.  Relevant metapackages: [ubuntu-edu-preschool](https://packages.ubuntu.com/bionic/misc/ubuntu-edu-preschool), [ubuntu-edu-primary](https://packages.ubuntu.com/bionic/misc/ubuntu-edu-primary), [ubuntu-edu-secondary](https://packages.ubuntu.com/bionic/misc/ubuntu-edu-secondary), and [ubuntu-edu-tertiary](https://packages.ubuntu.com/bionic/misc/ubuntu-edu-tertiary)

Edubuntu can be installed with:

`sudo apt update && sudo apt install -y edubuntu-desktop`

**Comment by zefanja** [comment]
Thanks. I will definitely have a look at some of these apps. BTW: Do you have a twitter account?

**Comment by TechnologyClassroom** [comment]
I am mostly just on github, reddit, and LinkedIn.

**Pull request merged**
